name: Update Submodule on Library Changes

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Update submodule to latest version
      run: |
        git submodule update --init --recursive
        git add libs/component-library
        git commit -m "Update component-library submodule"
        git push origin main
